GET http://localhost:3001/api/manual-register


###
POST http://localhost:3001/api/manual-register
Content-Type: application/json

{
  
   
   "email":"pratik@gmail.com",
   "name":"pratik",
   "password":"pratik"
   
   
}
###
DELETE http://localhost:3001/api/manual-register/13



###
GET http://localhost:3001/api/category

###
POST http://localhost:3001/api/category
Content-Type: application/json

{
   "category_name":"social skill"
}

###
DELETE http://localhost:3001/api/category/3

###
GET http://localhost:3001/api/products

###
POST http://localhost:3001/api/products/comment
Content-Type: application/json

{
   "user_id":3,
   "product_id":1,
   "comment_text":"this product is really nice"

}

###
GET http://localhost:3001/api/sessions


###
DELETE http://localhost:3001/api/sessions/101


###
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
   "email":"current@gmail.com",
   "password":"current"

}

###
POST http://localhost:3001/api/products/cart/1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoicHJhdGlrQGdtYWlsLmNvbSIsIm5hbWUiOiJwcmF0aWsiLCJwYXNzd29yZCI6IiQyYSQxMCRwcWFnaVZXV0lnU1BKbUlQdXRpcmx1U3dyMXVld0dXcEYxb011VjFKTFdDNExrczlXUlJTRyIsImFkZHJlc3MiOm51bGwsImNvbnRhY3QiOm51bGwsInNlc3Npb24iOjU3LCJpYXQiOjE3MDA3Mjc2NTEsImV4cCI6MTcwMDcyNzk1MX0.SU0MEfe_R2IlbszggWDg8YwKsdpDjDCH6xTd8A-Uqxs

###
DELETE  http://localhost:3001/api/products/cart/91

###
GET http://localhost:3001/api/products/cart

###
PUT http://localhost:3001/api/products/cart/110
Content-Type: application/json

{
   "quantity":1
   
}


###
GET  http://localhost:3001/api/session
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoiYXhpdGExMkBnbWFpbC5jb20iLCJuYW1lIjoiYWt4aXRhIiwicGFzc3dvcmQiOiIkMmEkMTAkYmp0b3VkdUtsTk1Sb0Y4REQ5ZGJnLndwRHBWWWxrWml1ZFdocnkzcXova2JmenhISTFYY0MiLCJhZGRyZXNzIjpudWxsLCJjb250YWN0IjpudWxsLCJzZXNzaW9uIjoyMiwiaWF0IjoxNzAwMzkzNzU4LCJleHAiOjE3MDAzOTM4MTh9.TraGaJaNZPmcJhHculory9b7o8aTs4iduDP6CsrYOHA
x-refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTcsImVtYWlsIjoiYXhpdGExMkBnbWFpbC5jb20iLCJuYW1lIjoiYWt4aXRhIiwicGFzc3dvcmQiOiIkMmEkMTAkYmp0b3VkdUtsTk1Sb0Y4REQ5ZGJnLndwRHBWWWxrWml1ZFdocnkzcXova2JmenhISTFYY0MiLCJhZGRyZXNzIjpudWxsLCJjb250YWN0IjpudWxsLCJzZXNzaW9uIjoyMiwiaWF0IjoxNzAwMzkzNzU4LCJleHAiOjE3MDAzOTQ2NTh9.NHfWqPPjP64O7FcMnTw5STu-AuOFzElEhgorHGglGyE

###
GET http://localhost:3001/api/login-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsImVtYWlsIjoiY3VycmVudEBnbWFpbC5jb20iLCJuYW1lIjoiY3VycmVudCIsInBhc3N3b3JkIjoiJDJhJDEwJE8yMmtwc2pyNDV1Q1dzYmhSUGM5eU9tZjR0L2tVdklSZVRtUkxVVjQyaHFRblYuTXJJZEhXIiwiYWRkcmVzcyI6bnVsbCwiY29udGFjdCI6bnVsbCwiY2FydEl0ZW1zIjpbeyJpZCI6MzMsInVzZXJfaWQiOjIwLCJwcm9kdWN0X2lkIjo0LCJxdWFudGl0eSI6MCwicHJpY2UiOjAsInRpbWVzdGFtcCI6IjIwMjMtMTEtMzBUMTA6NTc6NDIuNzE1WiJ9LHsiaWQiOjM0LCJ1c2VyX2lkIjoyMCwicHJvZHVjdF9pZCI6NCwicXVhbnRpdHkiOjAsInByaWNlIjowLCJ0aW1lc3RhbXAiOiIyMDIzLTExLTMwVDExOjA5OjIwLjEyNloifSx7ImlkIjozNSwidXNlcl9pZCI6MjAsInByb2R1Y3RfaWQiOjQsInF1YW50aXR5IjowLCJwcmljZSI6MCwidGltZXN0YW1wIjoiMjAyMy0xMS0zMFQxMTowOTozMS43OTdaIn0seyJpZCI6MzYsInVzZXJfaWQiOjIwLCJwcm9kdWN0X2lkIjozLCJxdWFudGl0eSI6MCwicHJpY2UiOjAsInRpbWVzdGFtcCI6IjIwMjMtMTItMDNUMDc6MjU6NTQuNzkxWiJ9XSwic2Vzc2lvbiI6MTEzLCJpYXQiOjE3MDE1ODkzNjksImV4cCI6MTcwMTU5MTE2OX0.jLwm7o_siGeXw9e4dpi4-ZtyIHyot6KOVk5femooJCU