GET http://localhost:3001/api/manual-register


###
POST http://localhost:3001//api/manual-register
Content-Type: application/json

{
   "username":"akxita",
   "name":"akxita",
   "password":"password",
   "email":"axita@gmail.com",
   "address":"ekantakuna",
   "contact":"7878787878"
   
}
###
DELETE http://localhost:3001/api/manual-register/9

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
   "username":"akxita",
   "password":"password"
   
}

###
GET http://localhost:3001/api/category

###
POST http://localhost:3001/api/category
Content-Type: application/json

{
   "category_name":"social skill"
}

###
DELETE http://localhost:3001/api/category/3

###
GET http://localhost:3001/api/products

###
POST http://localhost:3001/api/products/comment
Content-Type: application/json

{
   "user_id":3,
   "product_id":1,
   "comment_text":"this product is really nice"

}

###
GET http://localhost:3001/api/sessions


###
DELETE http://localhost:3001/api/sessions/2